"""Add placement risk table

Revision ID: 1fa1cbdfd243
Revises: bd1fedbd453c
Create Date: 2026-10-08 14:28:56.613998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa1cbdfd243'
down_revision: Union[str, Sequence[str], None] = 'bd1fedbd453c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_risk_scores',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('placement_risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('available_signals', sa.JSON(), nullable=False),
    sa.Column('missing_signals', sa.JSON(), nullable=False),
    sa.Column('assessment_metadata', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_risk_scores')
    # ### end Alembic commands ###
