"""Add scoring table

Revision ID: 38109f80527c
Revises: 79b7a0446d30
Create Date: 2026-10-08 14:20:20.885842

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38109f80527c'
down_revision: str | Sequence[str] | None = '79b7a0446d30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_success_scores',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(), nullable=False),
    sa.Column('domain_scores', sa.JSON(), nullable=False),
    sa.Column('available_domains', sa.JSON(), nullable=False),
    sa.Column('missing_domains', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_success_scores')
    # ### end Alembic commands ###
