"""Add student segment table

Revision ID: 3ec038198807
Revises: 1fa1cbdfd243
Create Date: 2026-10-08 14:39:02.943605

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ec038198807'
down_revision: str | Sequence[str] | None = '1fa1cbdfd243'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_segment_memberships',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('membership_type', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_segment_memberships')
    # ### end Alembic commands ###
