"""Initial schema

Revision ID: 79b7a0446d30
Revises: 
Create Date: 2026-10-08 14:13:28.325422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b7a0446d30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_students_academic_year'), 'students', ['academic_year'], unique=False)
    op.create_index(op.f('ix_students_department'), 'students', ['department'], unique=False)
    op.create_index(op.f('ix_students_semester'), 'students', ['semester'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_index(op.f('ix_students_year'), 'students', ['year'], unique=False)
    op.create_table('academic_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('internal_marks', sa.Float(), nullable=False),
    sa.Column('backlogs', sa.Integer(), nullable=False),
    sa.Column('subject_performance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester', 'academic_year', name='uq_academic_record')
    )
    op.create_index('idx_academic_student_term', 'academic_records', ['student_id', 'semester', 'academic_year'], unique=False)
    op.create_index(op.f('ix_academic_records_id'), 'academic_records', ['id'], unique=False)
    op.create_index(op.f('ix_academic_records_student_id'), 'academic_records', ['student_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('overall_attendance', sa.Float(), nullable=False),
    sa.Column('subject_attendance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester', 'academic_year', name='uq_attendance_record')
    )
    op.create_index('idx_attendance_student_term', 'attendance_records', ['student_id', 'semester', 'academic_year'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('engagement_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('events_count', sa.Integer(), nullable=False),
    sa.Column('clubs_count', sa.Integer(), nullable=False),
    sa.Column('hackathons_count', sa.Integer(), nullable=False),
    sa.Column('certifications_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester', 'academic_year', name='uq_engagement_record')
    )
    op.create_index('idx_engagement_student_term', 'engagement_records', ['student_id', 'semester', 'academic_year'], unique=False)
    op.create_index(op.f('ix_engagement_records_id'), 'engagement_records', ['id'], unique=False)
    op.create_index(op.f('ix_engagement_records_student_id'), 'engagement_records', ['student_id'], unique=False)
    op.create_table('feedback_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('student_satisfaction', sa.Float(), nullable=False),
    sa.Column('faculty_feedback', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester', 'academic_year', name='uq_feedback_record')
    )
    op.create_index('idx_feedback_student_term', 'feedback_records', ['student_id', 'semester', 'academic_year'], unique=False)
    op.create_index(op.f('ix_feedback_records_id'), 'feedback_records', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_records_student_id'), 'feedback_records', ['student_id'], unique=False)
    op.create_table('lms_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('login_frequency', sa.Float(), nullable=False),
    sa.Column('assignment_completion', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester', 'academic_year', name='uq_lms_record')
    )
    op.create_index('idx_lms_student_term', 'lms_records', ['student_id', 'semester', 'academic_year'], unique=False)
    op.create_index(op.f('ix_lms_records_id'), 'lms_records', ['id'], unique=False)
    op.create_index(op.f('ix_lms_records_student_id'), 'lms_records', ['student_id'], unique=False)
    op.create_table('placement_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('aptitude_score', sa.Float(), nullable=False),
    sa.Column('coding_score', sa.Float(), nullable=False),
    sa.Column('mock_interview_score', sa.Float(), nullable=False),
    sa.Column('placement_participation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_records_id'), 'placement_records', ['id'], unique=False)
    op.create_index(op.f('ix_placement_records_student_id'), 'placement_records', ['student_id'], unique=True)
    op.create_table('skill_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('technical_skill_score', sa.Float(), nullable=False),
    sa.Column('soft_skill_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_records_id'), 'skill_records', ['id'], unique=False)
    op.create_index(op.f('ix_skill_records_student_id'), 'skill_records', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_records_student_id'), table_name='skill_records')
    op.drop_index(op.f('ix_skill_records_id'), table_name='skill_records')
    op.drop_table('skill_records')
    op.drop_index(op.f('ix_placement_records_student_id'), table_name='placement_records')
    op.drop_index(op.f('ix_placement_records_id'), table_name='placement_records')
    op.drop_table('placement_records')
    op.drop_index(op.f('ix_lms_records_student_id'), table_name='lms_records')
    op.drop_index(op.f('ix_lms_records_id'), table_name='lms_records')
    op.drop_index('idx_lms_student_term', table_name='lms_records')
    op.drop_table('lms_records')
    op.drop_index(op.f('ix_feedback_records_student_id'), table_name='feedback_records')
    op.drop_index(op.f('ix_feedback_records_id'), table_name='feedback_records')
    op.drop_index('idx_feedback_student_term', table_name='feedback_records')
    op.drop_table('feedback_records')
    op.drop_index(op.f('ix_engagement_records_student_id'), table_name='engagement_records')
    op.drop_index(op.f('ix_engagement_records_id'), table_name='engagement_records')
    op.drop_index('idx_engagement_student_term', table_name='engagement_records')
    op.drop_table('engagement_records')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index('idx_attendance_student_term', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_academic_records_student_id'), table_name='academic_records')
    op.drop_index(op.f('ix_academic_records_id'), table_name='academic_records')
    op.drop_index('idx_academic_student_term', table_name='academic_records')
    op.drop_table('academic_records')
    op.drop_index(op.f('ix_students_year'), table_name='students')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_semester'), table_name='students')
    op.drop_index(op.f('ix_students_department'), table_name='students')
    op.drop_index(op.f('ix_students_academic_year'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
