"""Add academic risk table

Revision ID: bd1fedbd453c
Revises: 38109f80527c
Create Date: 2026-10-08 14:24:05.278663

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd1fedbd453c'
down_revision: str | Sequence[str] | None = '38109f80527c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_risk_scores',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('academic_risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('available_signals', sa.JSON(), nullable=False),
    sa.Column('missing_signals', sa.JSON(), nullable=False),
    sa.Column('assessment_period', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academic_risk_scores')
    # ### end Alembic commands ###
